UPDATE base_application_codeset SET display='Presumptive TB' WHERE display='TB suspected and referred for evaluation' ;
UPDATE base_application_codeset SET display='Currently on TPT' WHERE display='Currently on INH prophylaxis';
UPDATE base_application_codeset SET display='Confirmed TB' WHERE display='TB positive not on TB drugs';
UPDATE base_application_codeset SET display='Gene Xpert' WHERE display='GeneXpert';
UPDATE base_application_codeset SET display='Chest X-ray' WHERE display='CXR';
UPDATE base_application_codeset SET display='Chest X-ray' WHERE display='Chext Xray';
UPDATE base_application_codeset SET display='Treatment completed' WHERE display='Completed';
UPDATE base_application_codeset SET display='Treatment failed' WHERE display='Developed Active TB';
UPDATE base_application_codeset SET display='Currently on TPT' WHERE display='Currently on INH prophylaxis';
UPDATE base_application_codeset SET display='Confirmation (3-6 months after intense adherence counselling)' WHERE display='Confirmation';
UPDATE base_application_codeset SET display='Routine ' WHERE display='Repeat Test';
UPDATE base_application_codeset SET display='Clinical failure' WHERE display='Targeted Monitoring';
UPDATE base_application_codeset SET display='MHPSS/GBV' WHERE display='ATJ';
UPDATE base_application_codeset SET display='Community Mobilization' WHERE display='CBO';
UPDATE base_application_codeset SET display='Community Mobilization' WHERE display='CC';
UPDATE base_application_codeset SET display='Community Mobilization' WHERE display='EPOA';
UPDATE base_application_codeset SET display='HTS' WHERE display='ICT';
UPDATE base_application_codeset SET display='HTS' WHERE display='Index';
UPDATE base_application_codeset SET display='PMTCT' WHERE display='L&D';
UPDATE base_application_codeset SET display='Community Mobilization' WHERE display='OVC';
UPDATE base_application_codeset SET display='Community Mobilization' WHERE display='OVC Partner';
UPDATE base_application_codeset SET display='Community Mobilization' WHERE display='PE';
UPDATE base_application_codeset SET display='GBV' WHERE display='PEP';
UPDATE base_application_codeset SET display='PMTCT' WHERE display='Postnatal ward';
UPDATE base_application_codeset SET display='Community Mobilization' WHERE display='SM';
UPDATE base_application_codeset SET display='HTS' WHERE display='Walk-In';